services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - '59227:5432'
  mailhog:
    image: 'mailhog/mailhog'
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
