spring:
    jpa:
        show-sql: true
        properties:
          hibernate:
              format_sql: false
        hibernate:
            ddl-auto: none
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}?createDatabaseIfNotExist=true
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    docker:
        compose:
            enabled: ${COMPOSE_ENABLED}
            file: deploy/compose.yaml
    application:
        name: backend
        jwt_secret_key: ${JWT_SECRET_KEY}
        hash_salt: ${HASH_SALT}
        admin-key: ${ADMIN_KEY}
        host: ${CLIENT_HOST_NAME}
        cors:
            allowed-origins: ${ALLOWED_ORIGINS}
    mail:
        host: ${MAIL_HOST}
        port: ${MAIL_PORT}
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        sender: ${MAIL_SENDER}
        properties:
          mail:
              smtp:
                  auth: ${MAIL_AUTH}
                  starttls:
                      enable: ${ENABLE_STARTTLS}
logging:
    level:
      org:
          springframework: INFO
          hibernate:
              type:
                  descriptor:
                      sql: INFO
