spring:
    docker:
        compose:
            enabled: true
            file: compose.yaml
    application:
        name: backend
        jwt_secret_key: 'g1LOE{yPeRs>PB'
        hash_salt: 'MlSn0CDWTaajoF4uytLB5hQBTLdZNXRH'
